# Generated by Django 5.1.7 on 2025-04-05 12:50

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Данный',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='AboutObjects2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Данный 2',
                'verbose_name_plural': 'Данные 2',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовка Баннера')),
                ('description_banner', ckeditor.fields.RichTextField(verbose_name='Описание Баннера')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка О нас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание о нас')),
            ],
            options={
                'verbose_name': 'Настройки страницы о нас',
                'verbose_name_plural': 'Настройки страницы о нас',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbers', ckeditor.fields.RichTextField(verbose_name='номер телефона')),
                ('email', models.CharField(max_length=155, verbose_name='почта')),
                ('address', models.CharField(max_length=155, verbose_name='адрес')),
                ('links_email', models.URLField(verbose_name='Ссылка на почту')),
                ('links_address', models.URLField(verbose_name='Ссылка на адрес')),
            ],
            options={
                'verbose_name_plural': 'Настрокий контакты',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('photo', models.ImageField(upload_to='courses/', verbose_name='фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Продолжительность (мес.)')),
                ('discounted_price', models.IntegerField()),
                ('monthly_price', models.IntegerField()),
                ('color_theme', models.CharField(help_text='Цвет темы: light-purple, dark-blue, green и т.д.', max_length=50)),
                ('title_model', ckeditor.fields.RichTextField(verbose_name='Заголовка Модельного окна')),
                ('description_model', ckeditor.fields.RichTextField(verbose_name='Описание Модельного окна')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CoursesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233, verbose_name='заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'настройка стр курсов',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовок Баннер')),
                ('description_banner', ckeditor.fields.RichTextField(verbose_name='Описание Баннер')),
                ('title_about', models.CharField(max_length=155, verbose_name='Заголовок О нас')),
                ('image_about', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('description_about', ckeditor.fields.RichTextField(verbose_name='Описание О нас 1')),
                ('title_about2', models.CharField(max_length=155, verbose_name='описания материала')),
                ('description_about2', ckeditor.fields.RichTextField(verbose_name='Описание О нас 2')),
                ('description_about3', ckeditor.fields.RichTextField(verbose_name='Описание О нас 3')),
                ('description_about4', ckeditor.fields.RichTextField(verbose_name='Описание О нас 4')),
                ('popular_courses', models.CharField(max_length=155, verbose_name='Популярные курсы')),
                ('our_teachers', models.CharField(max_length=155, verbose_name='Наши преподы')),
                ('feedback', models.CharField(max_length=155, verbose_name='Заголоаок обратный связи')),
                ('feedback_description', ckeditor.fields.RichTextField(verbose_name='Описание обратной связи ')),
            ],
            options={
                'verbose_name_plural': 'Настрокий Главной Страницы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО преподавателя')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фото')),
                ('bio_title', models.CharField(default='Кто преподает?', max_length=255, verbose_name='Заголовок')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TypeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тип курсов')),
            ],
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.courses', verbose_name='Курс')),
            ],
            options={
                'verbose_name_plural': 'заявление на курсы',
            },
        ),
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_model', ckeditor.fields.RichTextField(verbose_name='Заголовка Модельного окна')),
                ('description_model', ckeditor.fields.RichTextField(verbose_name='Описание Модельного окна')),
                ('image', models.ImageField(upload_to='courses', verbose_name='Фото')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modals', to='academy.courses')),
            ],
            options={
                'verbose_name_plural': 'модельное окно',
            },
        ),
        migrations.CreateModel(
            name='CoursesProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academy.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Достижение')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='academy.teacher')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.typecourse', verbose_name='направление'),
        ),
    ]
