# Generated by Django 5.1.4 on 2025-04-01 09:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbers', ckeditor.fields.RichTextField(verbose_name='номер телефона')),
                ('email', models.CharField(max_length=155, verbose_name='почта')),
                ('address', models.CharField(max_length=155, verbose_name='адрес')),
            ],
            options={
                'verbose_name_plural': 'Настрокий контакты',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовок Баннер')),
                ('description_banner', ckeditor.fields.RichTextField(verbose_name='Описание Баннер')),
                ('title_about', models.CharField(max_length=155, verbose_name='Заголовок О нас')),
                ('image_about', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('description_about', ckeditor.fields.RichTextField(verbose_name='Описание О нас 1')),
                ('description_about2', ckeditor.fields.RichTextField(verbose_name='Описание О нас 2')),
                ('description_about3', ckeditor.fields.RichTextField(verbose_name='Описание О нас 3')),
                ('description_about4', ckeditor.fields.RichTextField(verbose_name='Описание О нас 4')),
                ('popular_courses', models.CharField(max_length=155, verbose_name='Популярные курсы')),
                ('our_teachers', models.CharField(max_length=155, verbose_name='Наши преподы')),
                ('feedback', models.CharField(max_length=155, verbose_name='Заголоаок обратный связи')),
                ('feedback_description', ckeditor.fields.RichTextField(verbose_name='Описание обратной связи ')),
            ],
            options={
                'verbose_name_plural': 'Настрокий Главной Страницы',
            },
        ),
    ]
