# Generated by Django 5.1.4 on 2025-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='links_address',
            field=models.URLField(default=1, verbose_name='Ссылка на адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='links_email',
            field=models.URLField(default=1, verbose_name='Ссылка на почту'),
            preserve_default=False,
        ),
    ]
