# Generated by Django 5.1.4 on 2025-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_contacts_links_address_contacts_links_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='title_about',
            field=models.CharField(max_length=155, verbose_name='описания материала'),
        ),
    ]
