# Generated by Django 5.1.4 on 2025-04-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_settings_title_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title_about2',
            field=models.CharField(default=1, max_length=155, verbose_name='описания материала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_about',
            field=models.CharField(max_length=155, verbose_name='Заголовок О нас'),
        ),
    ]
