# Generated by Django 5.1.4 on 2025-04-01 12:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_settings_title_about2_alter_settings_title_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория курсов',
                'verbose_name_plural': 'Категории курсов',
            },
        ),
        migrations.CreateModel(
            name='PageCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_courses', models.CharField(max_length=155, verbose_name='Заголовок Баннер')),
                ('description_courses', ckeditor.fields.RichTextField(verbose_name='Описание Баннер')),
            ],
            options={
                'verbose_name_plural': 'Настрокий Главной Страницы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(blank=True, choices=[('0-3', 'Starter (0-3 уровень)'), ('4-6', 'Intermediate (4-6 уровень)'), ('7-9', 'Advanced (7-9 уровень)')], max_length=20, null=True, verbose_name='Уровень')),
                ('duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обычная цена')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ежемесячный платеж')),
                ('is_profession', models.BooleanField(default=False, verbose_name='Профессия')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.coursecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
