# Generated by Django 5.1.4 on 2025-04-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_coursecategory_pagecourses_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('skill1', models.CharField(max_length=155, verbose_name='навык')),
                ('skill2', models.CharField(max_length=155, verbose_name='навык')),
                ('skill3', models.CharField(max_length=155, verbose_name='навык')),
                ('skill4', models.CharField(max_length=155, verbose_name='навык')),
                ('skill5', models.CharField(max_length=155, verbose_name='навык')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='images_about',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
    ]
