# Generated by Django 5.1.4 on 2025-04-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_teachers_settings_images_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecourses',
            options={'verbose_name_plural': 'Настрокий Страницы Курсов'},
        ),
    ]
