# Generated by Django 5.1.7 on 2025-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_pagecourses_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='images_about',
            new_name='images_about1',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='image',
            new_name='image_teachers',
        ),
        migrations.AddField(
            model_name='settings',
            name='images_about2',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='images_about3',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='images_about4',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='images_about5',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
    ]
