# Generated by Django 5.1.7 on 2025-04-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_rename_images_about_settings_images_about1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='images_about6',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='images_about7',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='images_about8',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фотка'),
            preserve_default=False,
        ),
    ]
