# Generated by Django 5.1.4 on 2025-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_settings_images_about6_settings_images_about7_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'об учителях'},
        ),
    ]
