# Generated by Django 5.1.7 on 2025-04-03 10:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_achievement_teacher_delete_teachers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Данный',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='AboutObjects2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Данный 2',
                'verbose_name_plural': 'Данные 2',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовка Баннера')),
                ('description_banner', ckeditor.fields.RichTextField(verbose_name='Описание Баннера')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка О нас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание о нас')),
            ],
            options={
                'verbose_name': 'Настройки страницы о нас',
                'verbose_name_plural': 'Настройки страницы о нас',
            },
        ),
    ]
