# Generated by Django 5.1.7 on 2025-04-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_aboutobjects_aboutobjects2_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='PageCourses',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about3',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about4',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about5',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about6',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about7',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='images_about8',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
