# Generated by Django 5.1.7 on 2025-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_remove_course_category_delete_pagecourses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(help_text='Например: Starter (0–3 уровень)', max_length=255)),
                ('photo', models.ImageField(upload_to='courses/', verbose_name='фото')),
                ('description', models.TextField()),
                ('details', models.TextField(help_text='Текст для модального окна (подробнее)')),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('monthly_price', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('language', models.CharField(choices=[('en', 'Английский'), ('it', 'айти'), ('ar', 'арабский'), ('ort', 'орт')], max_length=15)),
                ('color_theme', models.CharField(default='light-purple', help_text='Цвет темы: light-purple, dark-blue, green и т.д.', max_length=50)),
            ],
        ),
    ]
