# Generated by Django 5.1.7 on 2025-04-04 09:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('direction', models.CharField(max_length=255, verbose_name='направление')),
                ('photo', models.ImageField(upload_to='courses/', verbose_name='фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Продолжительность (мес.)')),
                ('discounted_price', models.IntegerField()),
                ('monthly_price', models.IntegerField()),
                ('color_theme', models.CharField(default=None, help_text='Цвет темы: light-purple, dark-blue, green и т.д.', max_length=50)),
                ('title_model', ckeditor.fields.RichTextField(verbose_name='Заголовка Модельного окна')),
                ('description_model', ckeditor.fields.RichTextField(verbose_name='Описание Модельного окна')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CoursesProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academy.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
