# Generated by Django 5.1.7 on 2025-04-04 12:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_feedback_courseapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_model', ckeditor.fields.RichTextField(verbose_name='Заголовка Модельного окна')),
                ('description_model', ckeditor.fields.RichTextField(verbose_name='Описание Модельного окна')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.courses')),
            ],
            options={
                'verbose_name_plural': 'модельное окно',
            },
        ),
    ]
