# Generated by Django 5.1.7 on 2025-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_coursesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='courses', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
