# Generated by Django 5.1.7 on 2025-04-04 13:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_coursesmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233, verbose_name='заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'настройка стр курсов',
            },
        ),
        migrations.AlterField(
            model_name='coursesmodel',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modals', to='academy.courses'),
        ),
        migrations.DeleteModel(
            name='CourseApplication',
        ),
    ]
