# Generated by Django 5.1.7 on 2025-04-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_courseapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseapplication',
            options={'verbose_name_plural': 'заявление на курсы'},
        ),
    ]
